name: test

on:
  push:

  
jobs:
  setup-packer:
    runs-on: ubuntu-latest
    name: Test setup-packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Packer Build
        uses: hashicorp/setup-packer@master
        with:
          command: version
          
      

